### User Registration
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "username": "Rocky",
  "email": "test1@gmail.com",
  "password": "12345678"
}
### User Registration
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "username": "Brocky",
  "email": "test12@gmail.com",
  "password": "12345678"
}

### User Login
POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
  "username": "Brocky",
  "password": "12345678"
}

> {%
    if (response && response.body) {
        const {accessToken} = response.body;
        client.global.set("accessToken", accessToken);
        console.log("Access token successfully set:", accessToken);

    } else {
        console.error("Response body is undefined or empty.");
    }
%}



### Create bank account
POST http://localhost:8080/user/bank-accounts/create
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "currencyType": "GBP"
}

### Create card
POST http://localhost:8080/user/cards/create
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "cardType": "DEBIT",
  "currencyType": "EUR"
}

### Withdraw
POST http://localhost:8080/user/atm/withdraw
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "transferDetailsCommand": {
    "cardId": 2,
    "amount": "700"
  },
  "cardDetailsConfirmationCommand": {
    "toCardNumber": "3041898399807265",
    "expirationDate": "2029-09-20",
    "cvv": 646
  }
}

### Deposit
POST http://localhost:8080/user/atm/deposit
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "transferDetailsCommand": {
    "cardId": 2,
    "amount": "700"
  },
  "cardDetailsConfirmationCommand": {
    "toCardNumber": "3041898399807265",
    "expirationDate": "2029-09-20",
    "cvv": 646
  }
}




### Transfer
POST http://localhost:8080/user/transfer
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "transferDetailsCommand": {
    "cardId": 1,
    "amount": "12.5"
  },
  "cardDetailsConfirmationCommand": {
    "toCardNumber": "4213617343899522",
    "expirationDate": "2029-09-14",
    "cvv": 398
  }
}

### Get cards
GET http://localhost:8080/user/cards
Authorization: Bearer {{accessToken}}



